# fly.toml app configuration file generated for gigamonkey-test-lite-fs on 2024-07-02T09:35:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gigamonkey-test-lite-fs"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "gtlfs"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
